export const workouts = [
  {
    name: "Chest",
    timeRep: 40,
    timeBreak: 20,
    exercises: [
      "Benchpressing",
      "Flies",
      "Push-Ups",
      "Pullovers on back",
      "Benchpressing, holding together",
      "V Draw Up",
      "Benchpressing",
      "Flies",
      "Push-Ups",
      "Pullovers on back",
      "Benchpressing, holding together",
      "V Draw Up",
    ],
  },
  {
    name: "Shoulders",
    timeRep: 40,
    timeBreak: 20,
    exercises: [
      "Push-Up backwards",
      "Plank Twist-Up Left",
      "Plank Twist-Up Right",
      "Tap Shoulders",
      "Pinky to Thumb",
      "Flapping, bent over",
      "Flapping, standing straight",
      "Lying Eight",
      "Prayers",
    ],
  },
  {
    name: "Triceps",
    timeRep: 40,
    timeBreak: 20,
    exercises: [
      "Benchpressing, holding together",
      "Triceppressing",
      "Triceppressing, outwards",
      "Pullovers, standing",
      "Push-Ups from Forearms",
      "Triceppressing Hold, Up/Horizontal/Down",
      "Benchpressing, holding together",
      "Triceppressing",
      "Triceppressing, outwards",
      "Pullovers, standing",
      "Push-Ups from Forearms",
      "Triceppressing Hold, Up/Horizontal/Down",
    ],
  },
  {
    name: "Back 1",
    timeRep: 40,
    timeBreak: 45,
    exercises: [
      "Pull Along Legs, bent over",
      "Pull Along Legs, bent over",
      "Pull Along Legs, bent over",
      "Romanian Deadlifts",
      "Romanian Deadlifts",
      "Romanian Deadlifts",
      "Pull up outwards, bent over",
      "Pull up outwards, bent over",
      "Pull up outwards, bent over",
    ],
  },
  {
    name: "Back 2",
    timeRep: 60,
    timeBreak: 0,
    exercises: [
      "Towel Breaker",
      "Superman",
      "Reachers",
      "Reverse Snowangels",
      "Lifting Arms backwards",
    ],
  },
  {
    name: "Biceps",
    timeRep: 40,
    timeBreak: 20,
    exercises: [
      "Drag Curls",
      "Curls, bent over, turn around",
      "Curls outwards",
      "Hammer Curls",
      "Curls inwards",
      "Hold Curls, Up/Horizontal/Down",
      "Drag Curls",
      "Curls, bent over, turn around",
      "Curls outwards",
      "Hammer Curls",
      "Curls inwards",
      "Hold Curls, Up/Horizontal/Down",
    ],
  },
  {
    name: "Abs",
    timeRep: 30,
    timeBreak: 0,
    exercises: [
      "Starfish",
      "Tongs",
      "Butterfly",
      "Hold + Mini Scissor Kicks",
      "Leg Drop Pull",
      "Russian Twist",
      "Flutter Kicks",
      "Roll In",
      "Plank Left",
      "Plank Right",
      "Plank",
      "Spider Plank",
      "False 8",
      "Mountain Climbers",
      "Sit Up + Hold",
      "Sit Up + 2 Punches",
      "Plank Crunch",
      "Hold Low",
      "Flies",
      "Hold Extreme",
    ],
  },
  {
    name: "Legs",
    timeRep: 30,
    timeBreak: 0,
    exercises: ["Haha, as if I would train legs"],
  },
];
